### PR TITLE
added msg for the airspeed plugin

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
While I agree that we do need an airspeed measurement, this PR only adds the message for the airspeed and not the sensor plugin.

Could you explain how you are using this message?

**Comment by addy1997** [comment]
> While I agree that we do need an airspeed measurement, this PR only adds the message for the airspeed and not the sensor plugin.
> 
> Could you explain how you are using this message?

Yes, I am working on the airspeed plugin and the associated `airspeed` SDF files and add them shortly. Hence, this msg file could be useful.

**Comment by addy1997** [comment]
@Jaeyoung-Lim, okay, I will add the plugin files `ASAP`. Meanwhile, please check this PR #24, It is useful. Apologies for the inconvenience.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 Please feel free to reopen the PR when the rest of the implementation is available


Thanks!

**Pull request closed without merging**
