### PR TITLE
Hello world plugin added

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
@addy1997 Ghank you for the contribution. Could you share the PR that was contributed to the original repo?

I am not sure if this is useful for everyone running ignition gazebo, since it is outputting information on the terminal that is not being used and already displayed on yhe gui.

Unless this information is not consumed by any component or is helpful of solving any problems I am not sure why we would want to run an additional plugin just to display that the simulation has been paused or not.

**Comment by addy1997** [comment]
@Jaeyoung-Lim,

[Here](https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/examples/plugin/hello_world/HelloWorld.cc) it is.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 I think this makes sense in the main repo, but still unsure why this is useful for running PX4 in ignition gazebo

**Comment by addy1997** [comment]
@Jaeyoung-Lim, 

I don't like arguing but just for the sake of answering your question.

I had two reasons for adding this plugin.

1. This plugin can be used as a specific hello world plugin for the PX4 simulation instead of an ignition gazebo.
2. There was a hello world plugin in the PX4 gazebo repository also.

Feel free to close this PR should you still find it pointless.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 Also not trying to argue here :smiley:

To be clear, I don't think(or never said) your PR is pointless - I am just not convinced that this repository is the right place to host it. It is hard to merge PRs why it is useful (as the PR description was originally empty) or that is not directly benefiting the functionality of this repository.

I think the helloworld plugin makes sense as an example, but as you did in the gz-sim repo I think the upstream ignition gazebo repository is a better place to host it, as you already did for gazebo.

This is an application specific integration for ignition gazebo so basic tutorials / examples being in the main repo would have a better impact for people integrating the plugin. If you are more interested in helping others integrating PX4 specific plugins, it would be great if the helloworld plugin could be adapted to implementing a specific sensor and then it would be quite useful for others using this repository.

**Comment by addy1997** [comment]
@Jaeyoung-Lim, I sincerely apologize for initiating this PR. I belatedly realize that arguments like these are not good on the professional front. You were correct. After all, it's your repository.

closing it. Thanks. I hope this didn't waste your time.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 No need to apologize, and I greatly appreciate your contribution!

I am also excited to see https://github.com/Auterion/px4-simulation-ignition/pull/23 be finished. This will greatly benefit the simulation.

**Pull request closed without merging**
